function tf = use_exact_endothelium_fluid_domain(par)
    tf = isfield(par, 'useExactEndotheliumFluidDomain') && ...
        (islogical(par.useExactEndotheliumFluidDomain) || ...
         isnumeric(par.useExactEndotheliumFluidDomain)) && ...
        logical(par.useExactEndotheliumFluidDomain);
end